export  default ImagePath  ={
img :require ('../Image/backgroundTop.png'),
logo: require('../Image/logo.png'),
backgroundImage: require('../Image/background.jpeg'),
Welcome: require('../Image/Welcome2.png'),
Home: require('../Image/welcome3.png'),
Home2: require('../Image/filter.png'),
Home3: require('../Image/search.png'),
iphone: require('../Image/img1.webp'),
img2: require('../Image/img2.png'),
img3: require('../Image/iphone.png'),
img4: require('../Image/Samsung.png'),
img5: require('../Image/oppo.png'),
img6: require('../Image/applesimple.jpg'),
img7: require('../Image/applesimple2.jpg'),
bike: require('../Image/deliveryman.png'),
meggie: require('../Image/meggie.png'),
lock: require('../Image/locked.png'),
google: require('../Image/search.png'),
facebook:require('../Image/facebook.png'),
boy : require('../Image/bikeride.png'),
girl: require('../Image/girlrest.png'),
profile: require('../Image/Profile.png'),
leftcross: require('../Image/lefticon.png'),
whiteimg: require('../Image/whiteimg.png'),
redheart: require('../Image/redheart.png'),



} 